<?php

return [
    'whatsapp_number' => '212645532991',
    'admin_email' => env('EASYPSI_ADMIN_EMAIL', env('MAIL_FROM_ADDRESS', 'hello@example.com')),
    'support_label' => 'Équipe EasyPsi',
    'plans' => [
        'tronc_commun' => [
            [
                'name' => 'Mensuel',
                'price' => '50 MAD',
                'duration' => 'Accès 30 jours',
                'description' => 'Tarif réservé au niveau tronc commun.',
            ],
            [
                'name' => '6 mois',
                'price' => '300 MAD',
                'duration' => 'Accès 180 jours',
                'description' => 'Formule tronc commun sur 6 mois.',
            ],
            [
                'name' => 'Annuel',
                'price' => '400 MAD',
                'duration' => 'Accès 365 jours',
                'description' => 'Formule tronc commun sur une année.',
            ],
        ],
        'autres_niveaux' => [
            [
                'name' => 'Mensuel',
                'price' => '100 MAD',
                'duration' => 'Accès 30 jours',
                'description' => 'Valable pour 1ère bac, 2ème bac et préparation de concours.',
            ],
            [
                'name' => '6 mois',
                'price' => '500 MAD',
                'duration' => 'Accès 180 jours',
                'description' => 'Formule 6 mois pour les autres niveaux.',
            ],
            [
                'name' => 'Annuel',
                'price' => '700 MAD',
                'duration' => 'Accès 365 jours',
                'description' => 'Formule annuelle pour les autres niveaux.',
            ],
        ],
    ],
    'locales' => [
        'fr' => [
            'html_lang' => 'fr',
            'dir' => 'ltr',
            'name' => 'Français',
            'short' => 'FR',
            'body_class' => 'login-page',
            'title' => 'EasyPsi | Connexion',
            'login' => [
                'title' => 'Connexion à votre compte',
                'subtitle_prefix' => 'ou',
                'subtitle_link' => 'Créer un compte',
                'register_page' => 'Créer un compte',
                'email' => 'Adresse email',
                'password' => 'Mot de passe',
                'forgot' => 'Mot de passe oublié ?',
                'forgot_title' => 'Réinitialiser le mot de passe',
                'forgot_submit' => 'Envoyer la demande',
                'forgot_note' => 'Entrez votre email pour enregistrer une demande de réinitialisation.',
                'forgot_success' => 'Si cet email existe, un lien de réinitialisation vient d’être envoyé.',
                'forgot_missing' => "Cet email n'existe pas dans la base de donnees.",
                'forgot_rate_limited' => 'Trop de demandes de reinitialisation. Veuillez reessayer dans quelques minutes.',
                'forgot_mail_error' => "Le service email est temporairement indisponible. Veuillez reessayer plus tard ou contacter l'administration.",
                'reset_title' => 'Choisir un nouveau mot de passe',
                'reset_submit' => 'Mettre à jour le mot de passe',
                'reset_success' => 'Votre mot de passe a été réinitialisé avec succès.',
                'remember' => 'Se souvenir de moi',
                'submit' => 'Se connecter',
                'note' => "L'activation de l'abonnement et du paiement se fait via WhatsApp après validation.",
                'admin' => 'Espace admin',
                'student' => 'Espace étudiant',
                'show_password' => 'Afficher le mot de passe',
                'name' => 'Nom complet',
                'phone' => 'Téléphone',
                'confirm_password' => 'Confirmer le mot de passe',
                'register_submit' => 'Créer mon compte',
                'register_title' => 'Créer votre compte',
                'register_note' => 'Vos informations sont enregistrées dans la table users de Laravel.',
                'create_account_message' => 'Bonjour EasyPsi, je souhaite creer un compte.',
                'forgot_message' => 'Bonjour EasyPsi, j\'ai oublie mon mot de passe.',
                'success_registered' => 'Compte créé avec succès. Vérifiez votre email pour activer votre compte.',
                'success_logged_in' => 'Connexion réussie.',
                'verify_email_title' => 'Vérifiez votre adresse email',
                'verify_email_note' => 'Nous avons envoyé un lien de vérification à votre boîte mail. Ouvrez-le pour activer votre compte.',
                'verify_email_resend' => 'Renvoyer le lien',
                'verify_email_sent' => 'Un nouveau lien de vérification a été envoyé à votre adresse email.',
                'verify_email_verified' => 'Votre email a été vérifié. Vous pouvez maintenant accéder à votre compte.',
                'verify_email_required' => 'Vous devez vérifier votre email avant de vous connecter.',
            ],
            'course' => [
                'title' => 'EasyPsi | Course Interface',
                'topline' => 'Cours, accompagnement et abonnement avec support WhatsApp',
            ],
            'admin' => [
                'title' => 'EasyPsi | Administration',
                'heading' => 'Tableau de bord administrateur',
                'summary' => 'Gérez les étudiants, les paiements WhatsApp, les cours et les abonnements depuis un seul espace.',
            ],
        ],
        'en' => [
            'html_lang' => 'en',
            'dir' => 'ltr',
            'name' => 'English',
            'short' => 'EN',
            'body_class' => 'login-page',
            'title' => 'EasyPsi | Login',
            'login' => [
                'title' => 'Log in to your account',
                'subtitle_prefix' => 'or',
                'subtitle_link' => 'Create an account',
                'register_page' => 'Create account',
                'email' => 'Email address',
                'password' => 'Password',
                'forgot' => 'Forgot password?',
                'forgot_title' => 'Reset your password',
                'forgot_submit' => 'Send request',
                'forgot_note' => 'Enter your email to record a password reset request.',
                'forgot_success' => 'If this email exists, a reset link has just been sent.',
                'forgot_missing' => 'This email does not exist.',
                'forgot_rate_limited' => 'Too many reset requests. Please try again in a few minutes.',
                'forgot_mail_error' => 'The email service is temporarily unavailable. Please try again later or contact the admin team.',
                'reset_title' => 'Choose a new password',
                'reset_submit' => 'Update password',
                'reset_success' => 'Your password has been reset successfully.',
                'remember' => 'Remember me',
                'submit' => 'Log in',
                'note' => 'Subscription activation and payment are handled through WhatsApp after admin review.',
                'admin' => 'Admin area',
                'student' => 'Student area',
                'show_password' => 'Show password',
                'name' => 'Full name',
                'phone' => 'Phone',
                'confirm_password' => 'Confirm password',
                'register_submit' => 'Create my account',
                'register_title' => 'Create your account',
                'register_note' => 'Your information is stored in Laravel\'s users table.',
                'create_account_message' => 'Hello EasyPsi, I would like to create an account.',
                'forgot_message' => 'Hello EasyPsi, I forgot my password.',
                'success_registered' => 'Account created successfully. Please verify your email to activate your account.',
                'success_logged_in' => 'Login successful.',
                'verify_email_title' => 'Verify your email address',
                'verify_email_note' => 'We sent a verification link to your email inbox. Open it to activate your account.',
                'verify_email_resend' => 'Resend link',
                'verify_email_sent' => 'A new verification link has been sent to your email address.',
                'verify_email_verified' => 'Your email has been verified. You can now access your account.',
                'verify_email_required' => 'You must verify your email before logging in.',
            ],
            'course' => [
                'title' => 'EasyPsi | Course Interface',
                'topline' => 'Courses, coaching and subscriptions with WhatsApp support',
            ],
            'admin' => [
                'title' => 'EasyPsi | Admin Dashboard',
                'heading' => 'Administrator dashboard',
                'summary' => 'Manage students, WhatsApp payments, courses and subscriptions from one place.',
            ],
        ],
        'ar' => [
            'html_lang' => 'ar',
            'dir' => 'rtl',
            'name' => 'العربية',
            'short' => 'AR',
            'body_class' => 'login-page',
            'title' => 'EasyPsi | تسجيل الدخول',
            'login' => [
                'title' => 'الدخول إلى حسابك',
                'subtitle_prefix' => 'أو',
                'subtitle_link' => 'إنشاء حساب',
                'register_page' => 'إنشاء حساب',
                'email' => 'البريد الإلكتروني',
                'password' => 'كلمة المرور',
                'forgot' => 'نسيت كلمة المرور؟',
                'forgot_title' => 'إعادة تعيين كلمة المرور',
                'forgot_submit' => 'إرسال الطلب',
                'forgot_note' => 'أدخل بريدك الإلكتروني لتسجيل طلب إعادة تعيين كلمة المرور.',
                'forgot_success' => 'إذا كان البريد موجودا، فقد تم إرسال رابط إعادة التعيين.',
                'forgot_missing' => 'هذا البريد الإلكتروني غير موجود.',
                'forgot_rate_limited' => 'تم إرسال عدد كبير من طلبات إعادة التعيين. يرجى إعادة المحاولة بعد بضع دقائق.',
                'forgot_mail_error' => 'خدمة البريد الإلكتروني غير متاحة مؤقتا. يرجى المحاولة لاحقا أو التواصل مع الإدارة.',
                'reset_title' => 'اختيار كلمة مرور جديدة',
                'reset_submit' => 'تحديث كلمة المرور',
                'reset_success' => 'تمت إعادة تعيين كلمة المرور بنجاح.',
                'remember' => 'تذكرني',
                'submit' => 'تسجيل الدخول',
                'note' => 'تفعيل الاشتراك والدفع يتمان عبر واتساب بعد مراجعة الإدارة.',
                'admin' => 'لوحة الإدارة',
                'student' => 'مساحة الطالب',
                'show_password' => 'إظهار كلمة المرور',
                'name' => 'الاسم الكامل',
                'phone' => 'الهاتف',
                'confirm_password' => 'تأكيد كلمة المرور',
                'register_submit' => 'إنشاء الحساب',
                'register_title' => 'إنشاء حساب جديد',
                'register_note' => 'يتم حفظ معلوماتك داخل جدول users في قاعدة بيانات Laravel.',
                'create_account_message' => 'مرحبا EasyPsi، أريد إنشاء حساب.',
                'forgot_message' => 'مرحبا EasyPsi، لقد نسيت كلمة المرور.',
                'success_registered' => 'تم إنشاء الحساب بنجاح. يرجى تأكيد بريدك الإلكتروني لتفعيل الحساب.',
                'success_logged_in' => 'تم تسجيل الدخول بنجاح.',
                'verify_email_title' => 'تأكيد البريد الإلكتروني',
                'verify_email_note' => 'أرسلنا رابط تأكيد إلى بريدك الإلكتروني. افتح الرابط لتفعيل الحساب.',
                'verify_email_resend' => 'إعادة إرسال الرابط',
                'verify_email_sent' => 'تم إرسال رابط تأكيد جديد إلى بريدك الإلكتروني.',
                'verify_email_verified' => 'تم تأكيد بريدك الإلكتروني. يمكنك الآن الدخول إلى حسابك.',
                'verify_email_required' => 'يجب تأكيد بريدك الإلكتروني قبل تسجيل الدخول.',
            ],
            'course' => [
                'title' => 'EasyPsi | واجهة الدروس',
                'topline' => 'دروس ومواكبة واشتراكات مع دعم واتساب',
            ],
            'admin' => [
                'title' => 'EasyPsi | الإدارة',
                'heading' => 'لوحة تحكم الإدارة',
                'summary' => 'قم بإدارة الطلبة والمدفوعات عبر واتساب والدورات والاشتراكات من مكان واحد.',
            ],
        ],
    ],
];
